apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: 92monkeys-project1
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        - containerPort: 50000
